### ISSUE TITLE
Create DR Plan

### ISSUE THREAD

**Issue by cohiggins** [bcgov/moodle#10]
Create disaster recovery plan for Moodle:

- Backups
- Fail to location/different pods
- Confirm restore process
- Confirm persistent storage options with BCDevExchange (silver/gold)
- Confirm timelines for silver > gold upgrade

Additionally, confirm how other products are handling DR.

**Comment by cohiggins** [comment]
Need to confirm what is required (impacts of using OpenShift, silver vs. gold).

**Comment by will-freshworks** [comment]
Merging in to-dos from separate back-up ticket.
- Document back-up task questions
- Provide best practice recommendations
- Jared to review Freshworks for strategy docs we can leverage

**Comment by tanvi0ahuja** [comment]
Need to check the status, comments needed for backup, automation, newer things, etc. wip - Warren, Kunal to update.

Automated backups not in place for the database and files. Warren is doing manual backups to mitigate this for now.
Database reversion has some issues with data migrations, its also causing an issue with manually adding users.
Updated moodle config to match a compatible version for 5.7
There was a build error yesterday that is being worked on. It is fixed by Warren, Red Hat has locked Warren out
WIP

**Comment by will-freshworks** [comment]
Automated database backups now complete for DEV

**Tasks remaining**
- Database backups for TEST and PROD
- 
- File backups for moodle ( @kkapoor-fresh )
- @warrenchristian1telus and @kkapoor-fresh to finish documentation on backup and restore process and move this documentation into markdown files in github

**Comment by warrenchristian1telus** [comment]
Automated backups have been implemented across all namespaces (dev, test, prod) and documentation has been published to provide instructions for manual restoration of files and/or database. 

backups of files and databases are done daily to a PVC using netapp-file-backup storage, which will also be backed up daily for redundancy and disaster recovery. BCDevOps will need to be contacted to access the netapp-file-backup files in the case of disaster recovery where local PVC data is lost, or if backups are required beyond what is stored in the accessible PVC.

https://teams.microsoft.com/l/entity/com.microsoft.teamspace.tab.wiki/tab::3d2b2d27-f743-4212-8fe9-12d3305396ad?context=%7B%22subEntityId%22%3A%22%7B%5C%22pageId%5C%22%3A2%2C%5C%22sectionId%5C%22%3A12%2C%5C%22origin%5C%22%3A2%7D%22%2C%22channelId%22%3A%2219%3A4ae78e8f77764b8193ae97b9eb5e54bb%40thread.tacv2%22%7D&tenantId=6fdb5200-3d0d-4a8a-b036-d3685e359adc
