### ISSUE TITLE
Contact Catalyst and ask if they can develop the necessary plugin

### ISSUE THREAD

**Issue by allanhaggett** [bcgov/moodle#112]

**Comment by allanhaggett** [comment]
David & I are meeting with Kathy and hopefully Matt (Wed May 18 @ 13:00) to inquire if they can author the plugin that we need, rather than having Warren do it (with me hindering/helping). If they can do it, great! If they cannot, then we will create an epic and a series of issues to work towards that progress ourselves.

Plugin requirements:
- Enable synchronization with CDATA endpoint, populating the external enrolments table
    - Must handle drops/un-enrol
    - Can Catalyst work on this with a mocked CDATA endpoint? (no direct access to our systems)
- Enable email notification to learner upon external enrolment (only happens with 'manual enrolment' method)

We also have an outstanding issue with chicken/egg user creation that we're essentially stuck upon.

**Comment by warrenchristian1telus** [comment]
@allanhaggett We should also ask Catalyst about the possibility of synchronizing users from SSO / KeyCloak. If we don't pre-populate the users, I'm not sure how we could enroll them and send the initial email. They may have some good recommendations / options.

**Comment by allanhaggett** [comment]
Catalyst can help! We are in the midst of scheduling time to discuss, but it's looking like Wednesday June 1 at 13:00 we'll be meeting to get fine-grained on requirements. From there, they say they will take 3 weeks for a first plugin deliverable which will then require a bunch of testing. We will create a series of tickets here for this work, and so closing this issue.
