### ISSUE TITLE
Determine drop dead dates for the Sept 14 HR 101 launch

### ISSUE THREAD

**Issue by GlenSeredynski** [bcgov/moodle#120]

**Comment by allanhaggett** [comment]
We are encountering numerous delays with getting the various pieces of the enrolment bridge puzzle together. At what point do we need to consider an alternative approach if the bridge cannot be completed and tested well enough in time for the September 14 launch of HR 101?

If the worst-case scenario happens and we cannot use the bridge, what do we do?

1. @allanhaggett (me) will investigate CSV roster export from ELM and import that manually into a Moodle course
2. Investigate the practicality of using an enrolment key that is distributed 
3. "mark yourself complete" might be necessary or can we "ad-hoc" (existing ELM completion info CSV import) back in?
4. Poll the LC working group (and elsewhere) for solutions
5. Seek guidance from Catalyst to see what options they might provide
