### ISSUE TITLE
Implement vanity URL ASAP

### ISSUE THREAD

**Issue by allanhaggett** [bcgov/moodle#197]
Apparently we can't use the URLs we're using:

"
I have been made aware that your Learning Curator app does not have its own vanity domain for your production environment and is instead using the OpenShift Wildcard cert. The OpenShift Wildcard can only be used for Dev/Test environments. You must obtain a vanity domain (your own private certificate) from Entrust through a Service Now request and tie that to your route. Please get this in place ASAP.
https://learningcurator.apps.silver.devops.gov.bc.ca/
https://moodle-950003-prod.apps.silver.devops.gov.bc.ca/
"

**Comment by allanhaggett** [comment]
I'm thinking: psamoodle.gww.gov.bc.ca

**Comment by warrenchristian1telus** [comment]
I'm wondering if we should consider getting dev/test sub-domains as well? This would make remembering and switching between environments easier for those of us who do it regularly, and help to keep things tidy.

Maybe something like:

psamoodle.gww.gov.bc.ca
dev.psamoodle.gww.gov.bc.ca
test.psamoodle.gww.gov.bc.ca

**Comment by allanhaggett** [comment]
https://learn.gww.gov.bc.ca/
