### ISSUE TITLE
Event Trigger Investigation

### ISSUE THREAD

**Issue by cohiggins** [bcgov/moodle#34]
Insert records into CDATA from course completion.

**Comment by warrenchristian1telus** [comment]
Event Trigger is now installed and working in prod. Initial tests have resulted in response errors. Issue is under investigation.

**Comment by warrenchristian1telus** [comment]
Triggered Events have been verified to work with email notifications. Still having some issues with POST to CDATA and event variable injection.

**Comment by cohiggins** [comment]
Ready for user testing
