### ISSUE TITLE
Automate deployment to PROD

### ISSUE THREAD

**Issue by freshjwarren** [bcgov/moodle#41]
Acceptance criteria: On the initiation of the Action, new images in TOOLS are picked up and deployed to PROD, where they are confirmed by manually accessing the PROD url.

**Comment by kkapoor-fresh** [comment]
Working on establshing the CI/CD and setting up MYSQL cluster in Prod namespace. Following tasks are involved
- Add "Deploy to Prod step"  with Manual interevention in the Github Actions workflow. Setup Prod env in Giithub
- Rollout MySQL cluster in Prod. Test if it is working independently
- Integrate Moodle containers to work with Mysql cluster.
- Access Prod application at https://moodle-gamma-950003-prod.apps.silver.devops.gov.bc.ca/
