### ISSUE TITLE
Continuous deployment to DEV

### ISSUE THREAD

**Issue by freshjwarren** [bcgov/moodle#42]
Acceptance criteria: When code is pushed to the dev branch, the build and deploy to DEV Actions are automatically triggered.

**Comment by kkapoor-fresh** [comment]
The Build and Deploy to DEV steps are automatically getting triggered on a commit.  The Action Pipeline runs successfully without any errors. However, it seems that a manual action is needed to successfully complete the deployment. Will look into the bug as part of issue #44.

**Comment by kkapoor-fresh** [comment]
Outcome: When a pull request is made to the main branch, the build and deploy to DEV Actions are automatically triggered. @freshjwarren This can be closed
