### ISSUE TITLE
Deployment to DEV creates URL error

### ISSUE THREAD

**Issue by freshjwarren** [bcgov/moodle#43]

**Comment by kkapoor-fresh** [comment]
The error message "Cannot write to DB" on the moodle browser url has been identified and fix put in place. The fix seems to be working fine and the DEV site is up for now. Should be able close this after a bit of testing with the pipeline.

**Comment by kkapoor-fresh** [comment]
The Moodle DEV URL is now accessible at https://moodle-gamma-950003-dev.apps.silver.devops.gov.bc.ca/

Closing this ticket. 
![image](https://user-images.githubusercontent.com/77285719/135125489-fc99178b-9296-4939-9d45-ad2423b2de56.png)

**Comment by kkapoor-fresh** [comment]
Closing this after review with @warrenchristian1telus
