### ISSUE TITLE
Investigate bcgovGUID -> Moodle mapping issue

### ISSUE THREAD

**Issue by allanhaggett** [bcgov/moodle#45]
Warren this is kind of a bummer:
https://tracker.moodle.org/browse/MDL-61789

"OAuth2 field mappings don't allow to choose internal profile fields"

In a nutshell, because bcgovGUID is a custom field, the Moodle code ignores it and doesn't write to the database. So, even though the UI makes it look like you can map a custom AD field to a Moodle profile field (non-custom), there is a bug that is preventing the field you choose from actually populating in the database. In this case, I tried mapping bcgovGUID -> ID Number as ID Number is a standard profile field, but it doesn't actually work. It looks like there is some work done to correct this and make it so that you can choose a custom AD field and map that properly to a custom Moodle profile field, but it is not yet working and has been outstanding for at least the past two years. I think there's a great opportunity here, if we can fix this, to contribute the patches back to Moodle. 

I'll update again when I know more...

**Comment by allanhaggett** [comment]
Warren responded:
"That is unfortunate. And certainly could be a good opportunity to contribute. I'm thinking that is it's been in the queue for 2+ years, it might be tricky...but we can certainly take a look. This could be a bit of a can of worms if we need to incorporate behat, etc. to do it (properly). https://docs.moodle.org/dev/Behat_integration Although they would likely be willing to help us out if we fix the actual problem."

**Comment by allanhaggett** [comment]
Warren and I are going to spend a couple of hours each investigating in order to determine if we need a consult or if we can fix ourselves.

**Comment by tanvi0ahuja** [comment]
WIP

**Comment by warrenchristian1telus** [comment]
Catalyst has determined that this can be resolved in 4 hours of development time. This work has been approved by David.

Standing by for updates.

**Comment by tanvi0ahuja** [comment]
Catalyst has estimated 4 hrs, but we need a better estimate on the time for them as it doesn't look like they have estimated properly for everything that might be involved.

Azure is providing GUID but we are not able to store the user IDs because of a Moodle bug.. cant map it to the user profile.

**Comment by allanhaggett** [comment]
Summary: Catalyst was able to patch the main issue referred to at the top here, and have had that deployed to Moodle Core! It's awesome, but we've run into a snag that we need to investigate a bit more: while the main issue with mapping the standard oauth fields to profile (regular and custom) is fixed, our oauth (AzureAD) is returning the bcgovGUID as a _custom_ field in the response (not part of the standard response), and for some reason it's not mapping it correctly. Not sure why, but something weird is going on as we seem to be able to change the field around indiscriminately and it populates the same value...
Action: Setup meeting with Warren for Monday to discuss in further detail.

**Comment by allanhaggett** [comment]
Moodle 
- initially talks to authorization endpoint, 
- receives auth token and uses that to
- calls userinfo endpoint to and uses that response to
- create user account 

![image](https://user-images.githubusercontent.com/47408983/152418821-99023b9c-197f-4951-82f8-2d481b2736d5.png)

- CITZ says they cannot encode bcgovGUID into the userinfo endpoint response.
- Met with Jared and Simen from freshworks to chat about Keycloak.
- We're taking info to Catalyst for advice

**Comment by allanhaggett** [comment]
@freshjwarren FYI

It turns out that getting up and running on Keycloak was trivial :)

https://bcgov.github.io/sso-requests

Most of the process is automated and it's well documented, so we were up and running in about 30 minutes in the -dev environment; then another hour or so to tease out some details (e.g. the attribute name in Keycloak is "idir_userid" and not "bcgovguid" as it is in AuzreAD) and do some testing. 

**Bottom line**: Keycloak returns the correct GUID with the userinfo_endpoint response by default and Moodle can read that and map it to the correct profile field by default with no intervention or further mucking about :) Our request for production credentials has been submitted and should be approved within the next 2-3 days. Setting it up in Moodle _should_ be seamless.

This was a big blocker issue that has now been removed! I'm going to wait until we're in production with some testing under our belt before I actually close this issue, but ... PHEW!!
