### ISSUE TITLE
Give Will permission to edit issue statuses across all relevant repos

### ISSUE THREAD

**Issue by will-freshworks** [bcgov/moodle#58]

**Comment by allanhaggett** [comment]
@will-freshworks now has "maintain" access to this repo. Happy to do so for https://github.com/bcgov/learningcurator as well but will wait for planning meeting to discuss further.

**Comment by will-freshworks** [comment]
@allanhaggett could I get access to update issue statuses etc. (I think "write" is sufficient) on all three projects please? I am doing some devops scrum-mastering and it would be very helpful to be able to update the board in our meetings.

**Comment by allanhaggett** [comment]
@will-freshworks I've updated you to "write" here, and added you with "write" on https://github.com/bcgov/learningcurator as well, but I don't know which 3rd project you are referring to?

**Comment by will-freshworks** [comment]
Thanks @allanhaggett . That seems to be working.

The 3rd project I'm working with Warren and Kunal on is https://github.com/bcgov/performance

**Comment by allanhaggett** [comment]
@will-freshworks I don't have access to the performance project; you'll have to ask Warren about it :)

**Comment by will-freshworks** [comment]
@warrenchristian1telus are you able to grant me "write" perms on https://github.com/bcgov/performance?

**Comment by warrenchristian1telus** [comment]
Sorry @will-freshworks but I only have admin on this repo. I can't help with performance or learningcurator.

**Comment by will-freshworks** [comment]
So who is the admin on performance 👀?

**Comment by warrenchristian1telus** [comment]
Not sure @will-freshworks - I can only see contributors. Kousthubha, Kunal, Jared and Dennis are on there. Not sure if they're admins. I would think Kunal has admin to be able to run / approve actions and such.

**Comment by kkapoor-fresh** [comment]
@will-freshworks I was able to provide you write access to performance repository

**Comment by will-freshworks** [comment]
All access is working. Thanks all
