### ISSUE TITLE
Automated backups

### ISSUE THREAD

**Issue by will-freshworks** [bcgov/moodle#61]
https://docs.moodle.org/311/en/Site_backup

**Acceptance Criteria**
- Automated DB snapshot with a customizable frequency and lookback window
- Automated file backup at the same frequency/lookback as the db backup (as much as possible)
- Uses the "backup" PVC type
- Test restoring from a backup to a fresh environment

**Comment by kkapoor-fresh** [comment]
The following tasks need to be completed.
1. Create deployment template for Backup container
2. Create build template for Backup continer image
3. Run Build and Deployment jobs to test the functionality.

**Comment by kkapoor-fresh** [comment]
Deployed a backup container in DEV. The container runs on cron schedule which can be managed using a configmap. Testing backup functionality now.

**Comment by kkapoor-fresh** [comment]
You should now see a db-backup container running in DEV.
To take backups, you can rsh in the container and run:
./backup.sh -1 - This will run one cycle of backup

The scheduled backups will run according to the ./backup.sh -s <cron schedule> defined in backup.conf . 
image.png
You could change the schedule through the config map.

The backups will be stored in /daily, /weekly and /monthly folders. Today's backup will go in /monthly as today is the last day of the month.

I have tested the backups and they seem to be working fine. You can see backups created in the daily and monthly folder. Results of backup script below:
image.png



Before restoring the actual DB, there is also a provision to verify your restore which does the following.

Verifying backups, backup.sh [-s] -v <databaseSpec/> [-f <backupFileFilter>]
Verify mode will restore a backup to the local server to ensure it can be restored without error. Once restored a table query is performed to ensure there was at least one table restored and queries against the database succeed without error. All database files and configuration are destroyed following the tests.

Here are the results of the Verification process. Looks clean

image.png

Actual restore can be done using the command below.

./backup.sh -r mysql/moodle

@warrenchristian1telus @freshjwarren @will-freshworks

**Comment by will-freshworks** [comment]
File backups to be triggered on the same schedule as the db backup and ideally saved to the same location on the backup PVC.

**Comment by will-freshworks** [comment]
Decided in meeting with @kkapoor-fresh and @warrenchristian1telus that moodledata backups can just be a periodic rsync over to a backup-type PVC (probably the same one as for the SQL backups) since these PVCs are regularly backed up by OCIO and hence we are protected against accidental deletion being propagated by rsync.

**Comment by warrenchristian1telus** [comment]
Automated backups have been verified and tested in dev & test namespaces.
