### ISSUE TITLE
Increase File Upload Limit and Update Database Collation

### ISSUE THREAD

**Issue by warrenchristian1telus** [bcgov/moodle#62]
Issues / Fixes:

1) Increase File Upload Limit from 200MB to 2GB to allow large course backup / restore operations
2) Error When Manually Creating User (Admin)
3) Error Deleting PCMPv207-V from Prod (Admin)

![image](https://user-images.githubusercontent.com/70002196/142281349-ff9a4c16-7d45-4761-a7a3-c87449f4169f.png)

![image](https://user-images.githubusercontent.com/70002196/142279484-14fecc32-7d30-4ef5-8653-d5ce25837dd6.png)

Note: Error Deleting may be related to backup process, rather than delete action.

I Suspect that there is a relation between #3 - Deleting / Restoration issue, and the DB collation issue (#2) fixed in:

[https://github.com/bcgov/moodle/commit/6c0cbf59e5f3aa810baa5b93ec843d4274183cc5#diff-d927b2424f40229747935aa45f7691abb3f6f10b36c15339b0807413b4a74686]

@kkapoor-fresh Please approve / deploy to production between 6pm and 7am PST to avoid interrupting any users.

@allanhaggett Please review tomorrow and let me know if you or Kristine are still having any issues.

If the Delete / Restore issue (#3) turns out to be unrelated to this patch, a new ticket should be created for it.

**Comment by kkapoor-fresh** [comment]
@warrenchristian1telus I have moved the latest changes to PROD. But I am getting the below upgrade screen , should I go ahead and upgrade?
![image](https://user-images.githubusercontent.com/77285719/142367535-6af13df9-9d91-4fb1-b6aa-0fe0306964fa.png)

**Comment by warrenchristian1telus** [comment]
Thanks @kkapoor-fresh - I've run the DB upgrade and have validated the following:

1) Increased maximum upload limit to 2GB:
![image.png](https://images.zenhubusercontent.com/5f6b6e00c344a38c20855fad/43d378d7-be29-43d0-b492-a09f8ba05c93)

2) Manual user creation - successful:
![image.png](https://images.zenhubusercontent.com/5f6b6e00c344a38c20855fad/e321df23-16eb-4cf4-9f3e-ebf8fa89d007)

3) Error deleting (or backup), I am getting an error when attempting a backup. I will create a separate ticket for this, as it's obviously not to do with the collation as expected.

![image.png](https://images.zenhubusercontent.com/5f6b6e00c344a38c20855fad/0f137d81-75ed-4d28-8630-5b2ef411740e)

**Comment by warrenchristian1telus** [comment]
There was an update to F2F plugin 5 days ago to fix deprecated get_all_user_name_fields() for Moodle 3.11.

I believe this is causing a compatibility issue with our 3.9 installation. I'm not sure if this means we can now upgrade Moodle core to 3.11. Hopefully this is the case.

See Commits on Nov 16, 2021: Fix-63:

https://github.com/catalyst/moodle-mod_facetoface/commits/MOODLE_311_STABLE/lib.php

https://github.com/catalyst/moodle-mod_facetoface/commit/6291bb14bced8db38aa83234ceea17bf2131c8da#diff-8f5ff72ef1cf59199cfc4bbf16f2475d09e448601242f0d2c51bb94bd4aa1395

**Comment by warrenchristian1telus** [comment]
Upload limit, database collation and backups all now tested successfully.
