### ISSUE TITLE
F2F Plugin not working - DB error

### ISSUE THREAD

**Issue by GregMoranBCPS** [bcgov/moodle#65]
I’m getting an error with the F2F plugin today. We had some lost learner quiz data so for one of the learners I was trying to manually add them to one of the sessions.

Module 3 webinar:
https://moodle-950003-prod.apps.silver.devops.gov.bc.ca/mod/facetoface/view.php?id=458

I click on the Attendees link for the first session and get the following error (attached)
![F2F_error](https://user-images.githubusercontent.com/91910317/142687437-4a271ee7-94c5-403f-8a30-b477f16295d1.jpg)

**Exception - Class 'core_user\fields' not found**

**If I need to re-create these sessions in the F2F plugin, can you let me know soon so we can avoid further issues with the learners?**

**Comment by GregMoranBCPS** [comment]
I tried re-creating a new session in a later module and I'm getting the same error.

**Comment by GregMoranBCPS** [comment]
Also tested sign-up and cancellation.
I was able to sign-up for a session, but when I tried to cancel my booking - it failed and gave the same error.

**Comment by allanhaggett** [comment]
I can replicate by attempting to add a new F2F session in [Richard's test course](https://moodle-950003-prod.apps.silver.devops.gov.bc.ca/course/view.php?id=9)

**Comment by allanhaggett** [comment]
Access logs show:

moodle.aro.devops.gov.bc.ca:80 10.97.6.1 - - [19/Nov/2021:20:57:01 +0000] "POST /lib/editor/atto/autosave-ajax.php HTTP/1.1" 200 296 "https://moodle-950003-prod.apps.silver.devops.gov.bc.ca/mod/facetoface/sessions.php?f=13" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:94.0) Gecko/20100101 Firefox/94.0"
[Fri Nov 19 20:57:01.551001 2021] [php7:notice] [pid 536] [client 10.97.6.1:3956] **Database transaction aborted automatically in /vendor/moodle/moodle/mod/facetoface/sessions.php,** referer: https://moodle-950003-prod.apps.silver.devops.gov.bc.ca/mod/facetoface/sessions.php?f=13
moodle.aro.devops.gov.bc.ca:80 10.97.6.1 - - [19/Nov/2021:20:57:01 +0000] "POST /mod/facetoface/sessions.php HTTP/1.1" 404 146405 "https://moodle-950003-prod.apps.silver.devops.gov.bc.ca/mod/facetoface/sessions.php?f=13" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:94.0) Gecko/20100101 Firefox/94.0"

**Comment by warrenchristian1telus** [comment]
At first glance, it looks like this could be a version conflict of some sort.

The class 'core_user/fields' is in Moodle 3.11 (/user/classes/fields.php)
https://github.com/moodle/moodle/tree/MOODLE_311_STABLE/user/classes

But not in 3.9:
https://github.com/moodle/moodle/tree/MOODLE_39_STABLE/user/classes

It seems strange to me that Face to Face would be trying to use classes from Moodle 3.11 as it only supports up to 3.9.

May be related to this Moodle issue (Resolved: 30/Mar/21):
https://tracker.moodle.org/browse/MDL-71099

Notes from Moodle docs:
https://docs.moodle.org/dev/User_fields
https://docs.moodle.org/dev/User_fields#Older_Moodle_versions

Again though, this should only be used in 3.11+, so not sure why it's coming up here.

Investigating.

**Comment by GregMoranBCPS** [comment]
Any update on this? Since it's now a few hours past, I'll need to notify the PM program this is an issue in Moodle.

**Comment by warrenchristian1telus** [comment]
Sorry @GregMoranBCPS, I haven't been able to figure out how to fix this yet.

I'm not sure about the impacts to F2F sessions, but I would expect that it will not function correctly.

I've tried restoring a few versions of the course in dev and test, and see that the error is not in test. This makes me think it is related to the recent upgrade. Determining exactly which component, and how to resolve it may take some time though.

https://moodle-950003-test.apps.silver.devops.gov.bc.ca/mod/facetoface/attendees.php?s=8&backtoallsessions=3

They are all using the same version of F2F, so I think it's either the Moodle version, or to do with the (previous) database collation issue - which could persist in the database.

In test (working) we have Moodle version 3.9.10 (Build: 20210913) (2020061510)
In prod/dev (failing) we have :                    3.9.11+ (Build: 20211116) (2020061511.02)

One issue we will likely run into is that any reversion of the site code to a previous version will require database reversion as well. The only ways to accomplish that are to either:

1) Revert to an older copy, from before the upgrade (losing any subsequent updates)
2) Install a fresh (empty) copy. This would revert all content and settings, but would give us a clean / functional copy that would eliminate any chance of previous data corruption (from collation issue).

My preference, to avoid longer term issues, would be the latter. We could of course run the scenario in dev first and see if it resolves our immediate issue.

This would involve:

- [ ] Deleting all database content
- [ ] Re-install Moodle
- [ ] Manually restore all necessary configurations (Azure SSO, etc.)
- [ ] Restore course content from backups (individually)

**Comment by GregMoranBCPS** [comment]
Hi Warren,

That is a pretty drastic change. Deleting all database content and re-installing Moodle would affect learners currently in a pilot run. Any chance we could explore other alternatives?

Open to a quick chat right now?

**Comment by GregMoranBCPS** [comment]
I'll send out a mtg invite for first thing Monday to discuss. Please do not wipe any data until we've had a chance to discuss.

I've notified the Program Lead for the course being piloted right now - and learners are currently working through course content all through till mid-December.

**Comment by allanhaggett** [comment]
I'm out and about so can't be thorough here, but the course backups contain the user data, so we can reset Moodle and not lose any data but the face to face session info (which is broken anyhow). We can chat more Monday, but it's all good :)

**Comment by warrenchristian1telus** [comment]
The course backups will contain all user / course info, so I don't think much should be lost with a full reinstall, but we should validate on dev first. Any encoding issues in backups could lead to them being imported along with a backup as well, if that's the issue here (which it could be, as it seems to be related to attendees).

**Comment by warrenchristian1telus** [comment]
Adding additional debug info:

![image](https://user-images.githubusercontent.com/70002196/142901502-00bcd873-04af-4172-b194-0b6d225b9e49.png)

From dev and prod URLs:

https://moodle-950003-dev.apps.silver.devops.gov.bc.ca/mod/facetoface/attendees.php?s=28&backtoallsessions=14
https://moodle-950003-prod.apps.silver.devops.gov.bc.ca/mod/facetoface/attendees.php?s=28&backtoallsessions=14

**Comment by GregMoranBCPS** [comment]
Session details for all five module webinars have been backed up. I've got the HTML code saved in case I need to rebuild the session times/dates.

**Comment by warrenchristian1telus** [comment]
@GregMoranBCPS @allanhaggett Dev has been updated, and initial testing looks good. Attendees have been restored and are now available. Please verify, and update this ticket with confirmation on whether to release to production.

https://moodle-950003-dev.apps.silver.devops.gov.bc.ca/mod/facetoface/attendees.php?s=38&backtoallsessions=19

**Comment by GregMoranBCPS** [comment]
Just checked and yeah appears to be there. I see F2F registrations (from before) as well as course content.
Looks good as far as I can see.

**Comment by GregMoranBCPS** [comment]
Also can confirm I can now see F2F registrants

**Comment by warrenchristian1telus** [comment]
I've also completed database and course backups for everything in production.

**Comment by warrenchristian1telus** [comment]
Sounds good. Shall I proceed with release to production now?

**Comment by GregMoranBCPS** [comment]
Yeah, I'd say go for it. Let me know when I can go back in and test.

**Comment by warrenchristian1telus** [comment]
Deployment succeeded. Initial testing looks good. I was pinging the site during the deployment as well, and didn't notice any downtime (for future reference). Please let me know if everything looks OK on your end, and we can close this ticket.

**Comment by GregMoranBCPS** [comment]
Looks good! Course content is still intact. Webinar session data is still intact. I am able to see the Attendee list. I am able to register for sessions as well as cancel sessions. And I was able to manually add learners to sessions.

Nice work Warren!!

**Comment by warrenchristian1telus** [comment]
Thanks Greg. Glad to hear it! Closing ticket as resolved.
