### ISSUE TITLE
Wierd message when clicking on Moodle Home

### ISSUE THREAD

**Issue by GregMoranBCPS** [bcgov/moodle#67]
Now getting a weird message whenever I try to select "Home" when in Moodle:
![Screenshot 2021-11-22 125803](https://user-images.githubusercontent.com/91910317/142934364-8b1d08fe-8c10-4af9-a41c-438365279ea6.png)

**Comment by GregMoranBCPS** [comment]
@warrenchristian1telus @allanhaggett

**Comment by warrenchristian1telus** [comment]
Hi @GregMoranBCPS @allanhaggett That message comes up for Admins whenever there is a Moodle upgrade which requires database (and/or plugin) changes. I've run the upgrade script, so it shouldn't appear again (until the next release which requires it).

I'm wondering if we should review admin accounts, and if we should really be using them for all existing admins? I think we should minimize the use of full site administrator roles, and use more creator / manager roles where possible.

Closing this issue, but feel free to let me know if I should create a new issue for admin role investigation / revisions. If need be, we could always adjust the capabilities of accounts, create new roles, etc.

I think we could avoid some risk and confusion if we define and assign the roles effectively.
