### ISSUE TITLE
Review Admin Roles, Implement Power Users

### ISSUE THREAD

**Issue by warrenchristian1telus** [bcgov/moodle#68]
As mentioned in #67, we should review Admin roles, and limit them to actual site admins who will be maintaining database updates and other admin functions.

We may need to create a new role of "Power User" or similar to provide the ability to edit themes.

After some investigation, it seems this may not be an option: https://tracker.moodle.org/browse/MDL-50377

It may be possible via plugin: https://moodle.org/plugins/tool_editrolesbycap

Or Course / Category themes: https://docs.moodle.org/311/en/Theme_settings#Allow_course_themes

Or we could allow additional Admins in dev (for theme editing), with reduced Admins in production that can migrate theme changes (first to test for validation, then to production once approved).

**Comment by warrenchristian1telus** [comment]
@GregMoranBCPS

**Comment by GregMoranBCPS** [comment]
We've got a few documents collected as well that will inform what each role in Moodle should be allowed to do. Would prefer a meeting to go over it in detail when we're ready to set up set permission role profiles.
