### ISSUE TITLE
File backup in DEV

### ISSUE THREAD

**Issue by will-freshworks** [bcgov/moodle#70]
Current plan, github action on a cron schedule calling `oc exec` to `rsync` moodledata over to a backup PVC.

File backup should be on the same cron schedule as the db backups.

File backups will need to be rotated to not run out of space.

File backups should not be on the same PVC as moodledata itself

**Comment by kkapoor-fresh** [comment]
Created a github workflow to copy files to a baclup location

**Comment by will-freshworks** [comment]
Backups to run at 1am PST

**Comment by will-freshworks** [comment]
Now that we've moved to rotating file-backups we should get this on the same schedule as the backup-container. Recommend using the same variable for the crontab for both to make certain they stay in sync.

**Comment by kkapoor-fresh** [comment]
1. Changed cron schedule for D backups to 1 AM Pacific. 
2. Created a workflow_dispatch event to trigger file backups. This will be converted to a scheduled cron, if all looks good
3. 
- Github action will use  'matrix' to run file backups for multiple environments like DEV, TEST, PROD
- The Github action will check for older file backups greater than n days and purge them.
- The github action will rsync the file backups to timestamped backup folders.

**Comment by kkapoor-fresh** [comment]
The file folders to be synced are pretty substantial in size. Even after creating a gzipped tar archive, the disk space doesn't come under 75%. The PVC volume size I am using is 5 GB. Perhaps we need to reduce the no of backups(currently, we are keeping last 5 backups) and  increase the Persistent storage to a high value but there is only so much it can be expanded to @will-freshworks @warrenchristian1telus @freshjwarren

**Comment by will-freshworks** [comment]
@kkapoor-fresh and @warrenchristian1telus have agreed to reduce the backups to 2, and the PVC has been expanded to 8gb
