### ISSUE TITLE
DB + File backup in PROD

### ISSUE THREAD

**Issue by will-freshworks** [bcgov/moodle#73]

**Comment by will-freshworks** [comment]
@allanhaggett could we get approval for rolling this out to moodle PROD in the next week outside of business hours? Since we are just switching on a backup process there should be no noticeable impact, but better safe than sorry.

cc @warrenchristian1telus @kkapoor-fresh

**Comment by allanhaggett** [comment]
@will-freshworks please proceed! thank you :)

**Comment by will-freshworks** [comment]
Db backup done, file backup still in progress

**Comment by kkapoor-fresh** [comment]
@will-freshworks @freshjwarren @warrenchristian1telus   File back ups  have been added to Production

**Comment by allanhaggett** [comment]
Thank you!
