### ISSUE TITLE
Documentation of backup and restore process

### ISSUE THREAD

**Issue by will-freshworks** [bcgov/moodle#74]

**Comment by kkapoor-fresh** [comment]
Documentation shared with Warren.

**Comment by will-freshworks** [comment]
Needs to have a section about deleting moodledata beforehand if required, viz. to not leave orphaned files behind, particularly on dev

**Comment by will-freshworks** [comment]
@kkapoor-fresh to investigate exactly how the restore process works, in particular:
- Does the backup container validate the backup after taking it?
- Does the backup container drop the contents of the database at beginning of the restore process?

**Comment by kkapoor-fresh** [comment]
The functioning of the verification and restore process have been clearly documented in https://github.com/BCDevOps/backup-container/blob/6ceb85429b4bcc57604f3d046223d1b8dab36403/docker/backup.usage

Verify Options:
  ================
    The verify process performs the following basic operations:
      - Start a local database server instance.
      - Restore the selected backup locally, watching for errors.
      - Run a table query on the restored database as a simple test to ensure tables were restored
        and queries against the database succeed without error.
      - Stop the local database server instance.
      - Delete the local database and configuration.

The verfication can be manual or scheduled as follows:
backup.sh [-s] -v <databaseSpec/>  where -s flag can be used for running it on schedule

Restore Options:
  ================
    The restore process performs the following basic operations:
      - **Drop and recreate the selected database.**
      - Grant the database user access to the recreated database
      - Restore the database from the selected backup file
@will-freshworks @warrenchristian1telus @freshjwarren

**Comment by kkapoor-fresh** [comment]
Shared with @warrenchristian1telus through email
@will-freshworks @freshjwarren

**Comment by warrenchristian1telus** [comment]
Backup and restore process has been verified and documented on the MS Teams Wiki: https://teams.microsoft.com/l/channel/19%3A4ae78e8f77764b8193ae97b9eb5e54bb%40thread.tacv2/tab%3A%3A3d2b2d27-f743-4212-8fe9-12d3305396ad?groupId=08283480-3b33-45cd-ab68-0c9d6ede80e0&tenantId=6fdb5200-3d0d-4a8a-b036-d3685e359adc
