### ISSUE TITLE
Upgrade Moodle from 3.9 to 3.11

### ISSUE THREAD

**Issue by warrenchristian1telus** [bcgov/moodle#76]
As the Face to Face plugin has been recently upgraded to support Moodle 3.11, we should update both Moodle core and F2F to current versions. This should allow for some time to test this combination in dev, and prepare for the upcoming security release which will include the oAuth2 patch from Catalyst to resolve our GUID issue.

**Comment by warrenchristian1telus** [comment]
Upgrade has been completed in dev. Testing looks good so far, and I've been able to successfully map the GUID to the user's idnumber.

@allanhaggett can you please verify on your end?

It will be in the user profile under Optional > ID number. I've also locked this field, along with email.

https://moodle-950003-dev.apps.silver.devops.gov.bc.ca

Once approved, we can migrate these changes to test and prod. Just let me know if we will need to schedule a safe time to migrate to production - after the current / next courses are complete.

**Comment by allanhaggett** [comment]
@warrenchristian1telus I can indeed login, but my ID Number under Optional section is blank. I tried logging out and then back in, but nothing.

I did test create a FaceToFace session and was able to do all the things there.

**Comment by warrenchristian1telus** [comment]
@allanhaggett I'm thinking / hoping that it's just because your account was already created. And possibly because I also locked ID number. Although when I check your account (or the others) in admin it seems to be unlocked. maybe because they were created before the lock rule was applied? I think that if you delete your SSO account it should populate when you re-create it via logon. Just re-tested with my account and it populated as expected. If that doesn't work, let me know and I'll take a closer look.

**Comment by allanhaggett** [comment]
OK so I promoted my manual account to site admin, demoted my SSO account from admin, then deleted it.

When I logged back in as SSO, it created the account and now the ID Number field is populated, but it is **not** populated with my actual BC Gov GUID (mine _ends_ with "9FFD").

**Comment by warrenchristian1telus** [comment]
@allanhaggett A step in the right direction. Not sure about the GUID mismatch. I'm using the mapping of id > idnumber. maybe id isn't the right field, but I tried with bcgovGUID, and it didn't do anything. Any suggestions on what the oAuth field would be for the GUID, if not "id" or "bcgovGUID"?

**Comment by allanhaggett** [comment]
Yeah I was kind of afraid of this. "bcgovGUID" is the name of the field; it is a "custom" AzureAD field that isn't part of the standard response.
The first thing we should do is verify with CITZ that the AzureAD application is setup to return this field _to this instance_. If it is, then we're looking at whole other kettle of fish. More soon.

**Comment by warrenchristian1telus** [comment]
All environments have been upgraded to Moodle 3.11

![image.png](https://images.zenhubusercontent.com/5f6b6e00c344a38c20855fad/6d6b63a7-7dbe-464e-9aad-8fcde465ab72)
