### ISSUE TITLE
Investigate Build issue while upgrading 3.9.X to 3.11.X

### ISSUE THREAD

**Issue by kkapoor-fresh** [bcgov/moodle#77]
Steps taken -
1. Fixed the code to enable start build command.
2. Initiated a fresh build through CI/CD pipeline

The new build seems to be failing because the MOODLE_BRANCH_VERSION Variable in docker file is referencing to an upstream branch that doesn't exist. The upstream branch is controlled by the environment variable in Docker file as follows

ENV MOODLE_BRANCH_VERSION MOODLE_39_STABLE(for 3.9)

We are using MOODLE_BRANCH_VERSION = MOODLE_11_STABLE(this doesnt't exist upstream)

Instead we might want to use MOODLE_311_STABLE for 3.11, perhaps.

@warrenchristian1telus  please confirm if MOODLE_311_STABLE should be good to go. 

@freshjwarren @will-freshworks

**Comment by warrenchristian1telus** [comment]
I fixed the Moodle branch version typo and the build completed successfully. I ran the required DB updates and verified that the site and GUID updates are working as expected.
