### ISSUE TITLE
Stabilize moodle build

### ISSUE THREAD

**Issue by will-freshworks** [bcgov/moodle#79]
Build currently pulls git branches that are being updated. Should be fixed on a codebase and upgrading should require changing versions/commit-ids manually somewhere.

**Comment by kkapoor-fresh** [comment]
This requires further discussion as per @warrenchristian1telus's email , so could be moved back to backlog.

**Comment by will-freshworks** [comment]
@kkapoor-fresh to research using imagestreamtags in openshift as a solution to this (cc @warrenchristian1telus)

**Comment by will-freshworks** [comment]
Decided to stick with Moodle branches. This means plugins might break in DEV without any explicit action since we are pulling in newer code automatically.
