### ISSUE TITLE
Test DB/file backup rollback in DEV or TEST

### ISSUE THREAD

**Issue by will-freshworks** [bcgov/moodle#85]

**Comment by will-freshworks** [comment]
@kkapoor-fresh to coordinate with @warrenchristian1telus on this

**Comment by kkapoor-fresh** [comment]
@will-freshworks @warrenchristian1telus @freshjwarren  Was able to fix the error while running the restore process. Tested the DB backup restore process in DEV and it works fine. Please see screenshot below
![image.png](https://images.zenhubusercontent.com/603e7d017ac89a48774c4630/4e3310fc-46f1-486c-a529-23b447be17f5)
