### ISSUE TITLE
Install Moodle Plugin - Collapsed Topics

### ISSUE THREAD

**Issue by warrenchristian1telus** [bcgov/moodle#89]
Install to dev, then test for review by Shannon & Greg.

https://moodle.org/plugins/format_topcoll

**Comment by warrenchristian1telus** [comment]
Changes are in dev for review. Once confirmed, this can be migrated to test.

**Comment by allanhaggett** [comment]
Closing as this is successfully in production now. Note: Moodle 4 makes this plugin moot as it's now supported in courses by default.
