### ISSUE TITLE
Install Moodle Plugin - Cerificate

### ISSUE THREAD

**Issue by warrenchristian1telus** [bcgov/moodle#90]
Install plugin to dev, then test for review by Shannon & Greg.

@allanhaggett Can you please confirm which one we want? It seems they are both current, but only the newer one is receiving feature updates, while the older version will only receive bug fixes.

https://moodle.org/plugins/mod_certificate
Or (newer)
https://moodle.org/plugins/mod_customcert

The newer one can be customized in the browser, while the older one requires PHP customization. This could affect how we manage / migrate changes, as the older PHP customization should integrate well with GitHub workflows, while the newer is most likely stored in the database, so would require alternate backup / migration techniques. After some research, it seems the new version includes backup / restore functionality, which appears to work similar to the course backups.

Apparently, both can be installed at once without issue, if we want to test and validate both options in the same environment.

**Comment by allanhaggett** [comment]
The older one being better for GH integration is a fantastic point. 

Install them both. We'll evaluate and if the older one doesn't fit, then we'll just remove it. 

Thanks!

**Comment by warrenchristian1telus** [comment]
https://github.com/bcgov/moodle/pull/103

**Comment by warrenchristian1telus** [comment]
These plugins have been implemented in dev. Awaiting testing / review before migrating (one of them) to test.

**Comment by allanhaggett** [comment]
Acknowledged! Thank you! I have brought this event to our course developers who are now in the process of reviewing and testing these. I'll be meeting with them again early next week to deep-dive and come back with feedback on which certificates plugin we want to use.

**Comment by allanhaggett** [comment]
We still need to make a final recommendation here. Notwithstanding any sustainability concerns from Warren, after conferring with the course dev team, we are hoping to stick with the newer of the two choices, though we don't have a very strong opinion as both options fulfill the requirements.

Not going to close this for now, but it's not a real priority IMHO so we should put it on the back burner until enrolment ELM bridge is completed,
