### ISSUE TITLE
Production Redirecting to Dev

### ISSUE THREAD

**Issue by warrenchristian1telus** [bcgov/moodle#91]
The production site is currently redirecting to the dev site.

- [x] Investigate root cause
- [x] Determine when started
- [x] If it has been happening for longer than a day, migrate content from dev to prod before fixing redirect, as all users/content will be in dev.

**Comment by kkapoor-fresh** [comment]
Fixed for now. Seems like incorrect config in env file.

**Comment by warrenchristian1telus** [comment]
@kkapoor-fresh I think the SITE_URL Environment Variable may have been overridden by the .env file in the ConfigMap. Or the Environmnet variables aren't being registered properly (in PHP). We should sort it out so that there's only one place for all the Environment Config.

**Comment by kkapoor-fresh** [comment]
@warrenchristian1telus Ideally the upgrades to the app should be done through the CI/CD pipeline  deployments only. I think what has happened is that the Prod pod has restrarted for some reason due to which the .env file has been overidden by default config from the image. A good solution would be to mount the config-map as  volume to the pod so that upgrades to application which are not done through the CI-CD don't result in any mismatched config changes in the .env file.

**Comment by warrenchristian1telus** [comment]
@kkapoor-fresh I think we need to ensure there is only one ENV for each environment. Right now, it meems maybe we have an image .env file, a ConfigMap .env file, and then the DeploymentConfig Environment variables. Dev and Test don't seem to have he moodle Configmap. Is it needed? Is that the issue? I'll create a separate ticket for that., and close this one as the main issue has been resolved.

**Comment by warrenchristian1telus** [comment]
@kkapoor-fresh This has happened to prod again today. We really need to get this resolved in a permanent way. This should probably be part of https://app.zenhub.com/workspaces/psa-devops-60f098ab875719001bce05fb/issues/bcgov/moodle/92 as well, but the sooner we can get this resolved the better.

**Comment by kkapoor-fresh** [comment]
@warrenchristian1telus I have fixed the issue  permannetly in DEV and TEST. The .env config should now persist without any issues across pod restarts/recreation. Please validate at your end once and I will roll this out to Prod thereafter.
