### ISSUE TITLE
Cleanup / Organize Environment Variables

### ISSUE THREAD

**Issue by warrenchristian1telus** [bcgov/moodle#92]
We have had issues in production with the site redirecting to dev due to an image update or pod restart. We need to ensure we have all the right environment variables populating the image/site.

Currently, in prod we have Environment Variables in: ConfigMap , DeploymentConfig, and possibly in the image .env file as well.

We can't have a populated .env file in our repo. Especially not one with DB host and password: https://github.com/bcgov/moodle/blob/main/.env

We'll need to change the password when we (re)move it.

I think we should migrate all environment variables into GitHub Environment secrets: https://github.com/bcgov/moodle/settings/environments/315982153/edit

We have a prod and test environment setup for the approvals, but to use environment variables here, we'll need one for dev as well (without the protection rule).

I think we can use .env files for local development, but it shouldn't be kept in git. At least, not a populated one. https://github.com/bcgov/moodle/commit/e64aa9f1b802edaefc08c81c138bf0e2c6141b79

My recommendation is to pass the GH Environment vars to the DC template: https://github.com/bcgov/moodle/blob/main/openshift/app/moodle-dc-persistent-template-new.json

I suppose this would be by adding the [GH variables](url), then passing them through the deployment? https://github.com/bcgov/moodle/blob/main/.github/workflows/deploy.yml

![image.png](https://images.zenhubusercontent.com/5f6b6e00c344a38c20855fad/01a011f2-42d4-4ad8-a9e1-09bc66c4678e)

I also think it would be good to automate where possible. Such as populating SITE_URL with ROUTE from:
export ROUTE="$(oc get route moodle -o jsonpath='{.spec.host}')"
echo "${APP} is exposed at 'https://'${ROUTE}" 

Rather than storing everything for each environment, we can share any that aren't - such as APP_NAME, DB_HOST, etc.

Please let me know if you agree with this approach, or have any recommendations.

**Comment by warrenchristian1telus** [comment]
@kkapoor-fresh After discussions with @will-freshworks we've decided the best approach is to use an .env file for each environment (local, dev, test, prod), with all secrets stored as such (DB password, etc.). The .env files should include all relevant environment variables, from Moodle config to DB_NAME to backup schedules and performance tuning vars for Apache/PHP/MySQL and Deployment/Pod configs (RAM, etc.). This way, we can adjust each environment and track changes in one file (say, increase RAM or PVC size in prod). As we're already doing for ${MOODLE_VOLUME_CAPACITY}, etc. in moodle-dc-persistent-template-new.json.

**Comment by kkapoor-fresh** [comment]
I have fixed the issue permannetly in DEV and TEST. The .env config should now persist without any issues across pod restarts/recreation. Please validate at your end once and I will roll this out to Prod thereafter.

**Comment by warrenchristian1telus** [comment]
Hi @kkapoor-fresh - can you please confirm if this has been completed in prod. If so, please close. If not, let's try get it migrated. Unless there is a blocker - in which case we should get that listed here.

**Comment by kkapoor-fresh** [comment]
@warrenchristian1telus Yes it's there in PROD. we should close this.
