### ISSUE TITLE
PVC Capacity for MySQL – need to purge binlogs on each backup to ensure we don’t keep filling storage and crashing the system

### ISSUE THREAD

**Issue by kkapoor-fresh** [bcgov/moodle#94]

**Comment by kkapoor-fresh** [comment]
Tuning parameter expire_logs_days set to 2 to automatically rotate bin logs. Monitoring this in DEV currently. Would be subsequently moved to other environments.

**Comment by will-freshworks** [comment]
Let's set to 6h across all envs and come back to it if it becomes an issue

**Comment by kkapoor-fresh** [comment]
As of MYSQL 5.7, the binary log expiry is cannot be set in seconds.  The parameter binlog_expire_logs_seconds is available in ver 8.0 and above. So, I have set the 5.7 parameter expire_log_days to a minimum value of 1 . The changes have been migrated to all environments.
@will-freshworks @freshjwarren @warrenchristian1telus
